import Head from 'next/head'

type Props = {
  children: React.ReactNode
}

export function LayoutHome({ children }: Props): JSX.Element {
  return (
    <div>
      <Head>
        <title>Portafolio | Marcos Ortiz</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>{children}</main>
    </div>
  )
}
